spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    properties:
      hibernate:
        globally_quoted_identifiers: false
  liquibase:
    enabled: false

flowable:
  process-definition-location-prefix: classpath*:/processes/**/
  database-schema: ''
